### ISSUE TITLE
TypeError when run w/ emcee 3.0.0

### ISSUE THREAD

**Issue by johnabsher** [better/convoys#118]
`Typeerror __init__() got an unexpected keyword argument 'dim' convoys` is thrown when attempting to run with emcee 3.0.0.

The code in question is in `regression.py` (~line 248):
```
sampler = emcee.EnsembleSampler(
    nwalkers=n_walkers,
    dim=dim,
    lnpostfn = generalized_gamma_loss,
    args=args,
)  
```

I was able to fix it by changing `dim` to `ndim` and `lnpostfn` to `log_prob_fn` - no other changes were required.

**Comment by johnabsher** [comment]
This is only an issue in the package version currently [hosted on pypi](https://pypi.org/project/convoys/#files)

**Comment by erikbern** [comment]
oh yeah, good point, i haven't uploaded the latest version to pypi yet. will do tonight. thanks!
