### ISSUE TITLE
Return posterior distribution from cdf function

### ISSUE THREAD

**Issue by conordewey3** [better/convoys#121]
For multi models, the user can pass `ci=True` and `cdf()` returns a tuple with the mean, lower bound, and upper bound of the confidence interval. 

In use cases where one wants to compare across groups, returning the posterior distribution itself is more desirable than summary metrics.

I'd like to add a parameter for the user to specify that they want the posterior distributions for each group. I'll link to the PR below.

**Comment by erikbern** [comment]
that makes sense conceptually, but we're just sampling from the posterior, so it will just be a crude estimate of the cdf. but i'm fine having a flag so it returns the full set of samples rather than a summary

**Comment by conordewey3** [comment]
Deprioritizing this for now!
