### ISSUE TITLE
Error in fit() method

### ISSUE THREAD

**Issue by holvi-german** [better/convoys#92]
Hey!
Awesome library - saved my day!

I've experienced an issue when trying to fit a model:
```
single.KaplanMeier.fit(B,T)
```
throws `TypeError: fit() missing 1 required positional argument: 'T'`.

Can not figure out what's the issue here.

**Comment by erikbern** [comment]
You need to instantiate the model first!

```python
model = single.KaplanMeier()
model.fit(B, T)
```

hope that makes sense!
